### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [hosodatomoya41/ZzzCrafter#64]
MVPリリースお疲れ様でした、下記の視点をもとにレビューいたします。

1. READMEから課題解決する実装がされているか&動いている
2. フレームワークの特性を活かし冗長なコードを書いていないか
3. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

## READMEから課題解決する実装がされているか&動いている
確認しました。LTGMです。

## フレームワークの特性を活かし冗長なコードを書いていないか
気になった箇所を挙げたのでご確認ください。
- users_controller.rb に「_,」の記載は何でしょうか。

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
気になった箇所を挙げたのでご確認ください。
- 機能が少ない印象を受けたので追加機能を実装した方が良いかと思いました。
- 使い方も初見のユーザーには分かりにくいUI/UX・動線になっているように感じたので、一旦ゼロベースでどういった導線が良いか検討してみましょう。
  - 例：ルーティンを選択、LINEのトーク画面に戻って送信ボタンを押さないと登録できないetc
  - => LINE上で全てを完結するようにした方が良いのではという意見もありました。
  - 登録したルーティーン一覧ページでは他の人の登録が表示されているように感じたので確認してください。

**Comment by hosodatomoya41** [comment]
レビュー頂きありがとうございます。

> users_controller.rb に「_,」の記載は何でしょうか。

`user.selected_issue_point`から返される２つの配列の内、１つ目の配列を受け取らないために記述していました。
しかし、不要だったので適切に書き換えました。ご指摘頂きありがとうございます。
[該当のcommit](https://github.com/hosodatomoya41/ZzzCrafter/commit/a70b5d9b6beb34e4f8fbc83166f929a0eb9dd3ce)

> 機能が少ない印象を受けたので追加機能を実装した方が良いかと思いました。
使い方も初見のユーザーには分かりにくいUI/UX・動線になっているように感じたので、一旦ゼロベースでどういった導線が良いか検討してみましょう。
例：ルーティンを選択、LINEのトーク画面に戻って送信ボタンを押さないと登録できないetc
=> LINE上で全てを完結するようにした方が良いのではという意見もありました。

機能に関して、下記のものを追加で考えております。
・ご提案頂いた、LINE上で全て完結できるようにする
・ルーティーンの追加、編集やユーザー管理を行える管理画面を作成
・高度な機能のレコメンドを実装し、おすすめのルーティーンの機能をより発展させる

UI・UXに関して、LINE上で全て完結できるようにし、リッチメニューやLinebotの返答を駆使して単純で分かりやすい導線にしようと考えています。

> 登録したルーティーン一覧ページでは他の人の登録が表示されているように感じたので確認してください。

ご指摘ありがとうございます。修正しました。
[該当のcommit](https://github.com/hosodatomoya41/ZzzCrafter/commit/ddafaa50836d6d7dfd35d9301ecee146048048b2)

以上、ご確認よろしくお願い致します。
